services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "7728246732:AAEZQHfP5-5rudq__beXrcugfUH3dBqEwiw"
